# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-11-23T11:03:17+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Fraction(BaseModel):
    numerator: int
    denominator: int


class Mode(Enum):
    Major = "Major"
    Minor = "Minor"


class NoteName(BaseModel):
    value: int


class Octave(BaseModel):
    value: int


class PartId(Enum):
    SOPRANO = "SOPRANO"
    ALTO = "ALTO"
    TENOR = "TENOR"
    BASS = "BASS"


class Pitch(BaseModel):
    octave: Octave
    note_name: NoteName


class Rest(BaseModel):
    pass


class ScoreAttrs(BaseModel):
    is_tied_start: bool


class Species(Enum):
    first = "first"
    second = "second"
    third = "third"
    fourth = "fourth"
    fifth = "fifth"


class CounterpointRequest(BaseModel):
    cf: list[str]
    key: str
    cf_part_id: PartId
    part_id: PartId
    species: Species


class Duration(BaseModel):
    value: Fraction


class Key(BaseModel):
    tonic: NoteName
    mode: Mode


class Note(BaseModel):
    value: Pitch | Rest
    duration: Duration
    attribute: ScoreAttrs


class TimeSignature(BaseModel):
    beats: int
    beat_type: Duration


class Measure(BaseModel):
    notes: list[Note]


class Score(BaseModel):
    parts: dict[str, list[Measure]]


class FullScore(BaseModel):
    key: Key
    time_signature: TimeSignature
    body: Score
