rules = [
  OrganizeImports
]

targetDialect = Scala3

OrganizeImports {
  groupedImports = AggressiveMerge
  expandRelative = true
  wildcardThreshold = 3
  groups = ["re:javax?\\.", "scala.", "*"]
  removeUnused = true
}
